### ISSUE TITLE
.base doesn't work when setting resources.Angular.base in application config

### ISSUE THREAD

**Issue by Cahdek** [Awnage/AngularZF1#1]
Documentation says to set .base in application config. Since this is a fork of the ZendX_Jquery_Component, the correct value should be resources.Angular.localpath OR change the switch statement to look for base instead of localpath

**Comment by Cahdek** [comment]
Additionally, setting localpath isn't being parsed correctly.

Setting resources.Angular.localpath = "/js/angular", you get a script tag as 
`<script src="/js/angular"></script>`

Additional plugins are loading correctly, but the base angular is not.

Fixed this by changing:

```
protected function _getAngularLibraryPath()
    {
        if($this->_angularLibraryPath != null) {
            $source = $this->_angularLibraryPath;
```

to 

```
protected function _getAngularLibraryPath ()
    {
        if ($this->_angularLibraryPath != null) {
            $source = $this->_angularLibraryPath .
                     ($this->_minified == true ? AngularZF1_Angular::CDN_ANGULAR_MIN_PATH_GOOGLE : AngularZF1_Angular::CDN_ANGULAR_PATH_GOOGLE);
```

in Angular/View/Helper/Angular/Container.php

**Comment by Awnage** [comment]
Awesome to see someone else benefiting from this. If you make a pull request, I am sure @bignall will have a look and give you the thumbs up.

**Comment by Cahdek** [comment]
Thanks! I've submitted the pull request. Glad I found this plugin! Great job!

**Comment by bignall** [comment]
Thanks so much! I'm glad to see it helping more people!  Thanks for the merge request with the fixes. I'll get it merged.

**Comment by bignall** [comment]
Closing with merged pull request
